Repository jhnc-oss/yocto-manifests, pull requests merged in 2023-08, with the labels that each got.

#35 switch to kirkstone
  default.xml
Labels: enhancement

#37 Backports for Dunfell
  LICENSE
  README.md
  default.xml
Labels: yocto: dunfell

#38 Mirror main to kirkstone
  .github/workflows/sync-main.yml
  README.md
Labels: documentation, ci
